#
# Project: Serial-TCP/IP bridge
# Author:  Petr Zemek, xzemek02@stud.fit.vutbr.cz
#
# Usage:
#   - create documentation:          make
#   - clean:                         make clean
#

# Create documentation
all:
	# Program documentation:
	make -C ./prog/
	# Project documentation:
	make -C ./proj/

# Cleaning
clean:
	make -C ./prog/ clean
	make -C ./proj/ clean
