#
# GNU Makefile
#
# Project:  POS 2009 (3)
# Author:   Petr Zemek, xzemek02@stud.fit.vutbr.cz
# Encoding: iso8859-2
#

CC=gcc
CFLAGS=-ansi -pedantic -W -Wall -g -D_REENTRANT -lpthread

xzemek02:

clean:
	rm -f xzemek02 core*

# End of file
