#
# Project: Serial-TCP/IP bridge
# Author:  Petr Zemek, xzemek02@stud.fit.vutbr.cz
#
# Usage:
#   - create program documentation:  make
#   - clean:                         make clean
#

# Doxygen command
DOXYGEN = doxygen

# Create program documentation
all:
	$(DOXYGEN) Doxyfile

# Cleaning
clean:
	rm -rf ./html/*
