#
# GNU Makefile
#
# Project:  POS 2009 (1)
# Author:   Petr Zemek, xzemek02@stud.fit.vutbr.cz
# Encoding: iso8859-2
#

CC=gcc
CFLAGS=-ansi -pedantic -W -Wall -g

fork:

clean:
	rm -f fork core*

# End of file
