#!/usr/bin/env python
# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.3 on Wed Oct  7 22:13:19 2009
#
# Project: VYPe - Conversion from regular expressions to finite automata
# Authors:
#     Libor Polčák, xpolca03@stud.fit.vutbr.cz
#     Petr Zemek, xzemek02@stud.fit.vutbr.cz
# Date: 4.10.2009
#

import wx
from MainFrame import MainFrame

class VYPe2009(wx.App):
    def OnInit(self):
        wx.InitAllImageHandlers()
        app = MainFrame(None, -1, "")
        self.SetTopWindow(app)
        app.Show()
        return 1

# end of class VYPe2009

if __name__ == "__main__":
    VYPe2009 = VYPe2009(0)
    VYPe2009.MainLoop()
